// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TrieDemo$ReactHooksTemplate = require("./TrieDemo.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(TrieDemo$ReactHooksTemplate.make, { }), "index3");

/*  Not a pure module */
